print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Qual é a sua idade? "))
print(f"Tu tens {idade} anos...")
print("O conhecimento é a luz que ilumina o caminho do futuro.")
print("Cada linha de código é um passo em direção ao conhecimento.")
print("Programar é transformar ideias em realidade.")
print("Ainda bem que computadores não reviram os olhos quando cometemos erros.")
print("É estranho pensar que o computador só entende isso porque alguém inventou tudo do zero.")
print("É curioso como a gente passa a vida inteira tentando descobrir quem é, mas quase nunca sabe o que responder quando alguém pergunta.")
print("Professor, se errar faz parte do aprendizado, então um código cheio de erros significa que estou aprendendo muito rápido?")
print("Não sei mais o que escrever, então vou começar a numerar as próximas linhas.")
