print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Qual é a sua idade? "))
print(f"Tu tens {idade} anos...")
print("O conhecimento é a luz que ilumina o caminho do futuro.")
print("Cada linha de código é um passo em direção ao conhecimento.")
print("Programar é transformar ideias em realidade.")
print("Ainda bem que computadores não reviram os olhos quando cometemos erros.")
print("É estranho pensar que o computador só entende isso porque alguém inventou tudo do zero.")